version: "3"
services:
  es:
    image: elasticsearch:6.8.13
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  web:
    image: reneab/food-trucks
    # build: . # for build at each run
    # environment:
    #   - DEBUG=True # for hot reload
    container_name: foodtrucks-web
    command: python3 app.py
    depends_on:
      - es
    ports:
      - 5000:5000
    volumes:
      - ./flask-app:/opt/flask-app
volumes:
    esdata1:
      driver: local
